const QuestionsList = [
  {
    question: "What is the capital of France?",
    options: ["Berlin", "Madrid", "Paris", "Rome"],
    answer: "Paris",
    id: 1,
    type: null,
  },
  {
    question: "Who wrote 'Hamlet'?",
    options: [
      "Charles Dickens",
      "William Shakespeare",
      "Mark Twain",
      "Jane Austen",
    ],
    answer: "William Shakespeare",
    id: 2,
    type: null,
  },
  {
    question: "What is the chemical symbol for water?",
    options: ["O₂", "H₂O", "CO₂", "NaCl"],
    answer: "H₂O",
    id: 3,
    type: null,
  },
  {
    question: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
    answer: "Mars",
    id: 4,
    type: null,
  },
  {
    question: "How many continents are there on Earth?",
    options: ["5", "6", "7", "8"],
    answer: "7",
    id: 5,
    type: null,
  },
  {
    question: "What does HTML stand for?",
    options: [
      "Hyper Text Markup Language",
      "High Tech Machine Learning",
      "Hyper Transfer Main Line",
      "Home Tool Markup",
    ],
    answer: "Hyper Text Markup Language",
    id: 6,
    type: null,
  },
  {
    question: "What is the value of 2 + 3?",
    options: ["4", "5", "6", "7"],
    answer: "5",
    id: 7,
    type: null,
  },
  {
    question: "Which programming language is used for web development?",
    options: ["Python", "C++", "JavaScript", "Swift"],
    answer: "JavaScript",
    id: 8,
    type: null,
  },
  {
    question: "What is the largest mammal?",
    options: ["Elephant", "Blue Whale", "Giraffe", "Dolphin"],
    answer: "Blue Whale",
    id: 9,
    type: null,
  },
  {
    question: "Which gas do plants absorb from the atmosphere?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
    answer: "Carbon Dioxide",
    id: 10,
    type: null,
  },
  {
    question: "Who is the founder of Microsoft?",
    options: ["Steve Jobs", "Elon Musk", "Bill Gates", "Mark Zuckerberg"],
    answer: "Bill Gates",
    id: 11,
    type: null,
  },
  {
    question: "What is 10 multiplied by 2?",
    options: ["10", "20", "30", "40"],
    answer: "20",
    id: 12,
    type: null,
  },
  {
    question: "Which component is used in React to manage state?",
    options: ["useEffect", "useState", "useReducer", "useRef"],
    answer: "useState",
    id: 13,
    type: null,
  },
  {
    question: "What does CSS stand for?",
    options: [
      "Creative Style Sheets",
      "Cascading Style Sheets",
      "Computer System Style",
      "Colorful Style System",
    ],
    answer: "Cascading Style Sheets",
    id: 14,
    type: null,
  },
  {
    question: "What is the boiling point of water in Celsius?",
    options: ["50°C", "75°C", "100°C", "150°C"],
    answer: "100°C",
    id: 15,
    type: null,
  },
  {
    question: "Which data structure uses LIFO (Last In, First Out)?",
    options: ["Queue", "Stack", "Array", "Linked List"],
    answer: "Stack",
    id: 16,
    type: null,
  },
  {
    question: "Which of the following is NOT a JavaScript framework?",
    options: ["React", "Angular", "Vue", "Django"],
    answer: "Django",
    id: 17,
    type: null,
  },
  {
    question: "Who painted the Mona Lisa?",
    options: [
      "Vincent van Gogh",
      "Pablo Picasso",
      "Leonardo da Vinci",
      "Claude Monet",
    ],
    answer: "Leonardo da Vinci",
    id: 18,
    type: null,
  },
  {
    question: "What is the speed of light?",
    options: ["300,000 km/s", "150,000 km/s", "100,000 km/s", "500,000 km/s"],
    answer: "300,000 km/s",
    id: 19,
    type: null,
  },
  {
    question: "Which country invented paper?",
    options: ["Egypt", "China", "Greece", "India"],
    answer: "China",
    id: 20,
    type: null,
  },
  {
    question:
      "Write a JavaScript function to add two numbers. The function should take two parameters and return their sum.",
    exampleInput: "addNumbers(5, 3)",
    expectedOutput: "8",
    sampleSolution: "function addNumbers(a, b) {\n  return a + b;\n}",
    type: "coding",
    id: 21,
  },
  {
    question:
      "Write a JavaScript function to find the factorial of a given number.",
    exampleInput: "factorial(5)",
    expectedOutput: "120",
    sampleSolution:
      "function factorial(n) {\n  if (n === 0 || n === 1) return 1;\n  return n * factorial(n - 1);\n}",
    type: "coding",
    id: 22,
  },
  {
    question: "Write a JavaScript function to reverse a string.",
    exampleInput: "reverseString('hello')",
    expectedOutput: "olleh",
    sampleSolution:
      "function reverseString(str) {\n  return str.split('').reverse().join('');\n}",
    type: "coding",
    id: 23,
  },
];

export default QuestionsList;
