import { Home, Login, PageNotFound, Result, Signup } from "../pages/Pages";

export const RoutingPathDatas = [
  {
    id: 1,
    name: "Login",
    components: <Login />,
    auth: true,
    show: false,
    exact: true,
    index: true,
    icon: "",
    path: "/",
  },
  {
    id: 2,
    name: "Signup",
    components: <Signup />,
    auth: true,
    show: false,
    exact: true,
    index: true,
    icon: "",
    path: "/signup",
  },
  {
    id: 3,
    name: "Home",
    components: <Home />,
    auth: false,
    show: false,
    exact: true,
    index: true,
    icon: "",
    path: "/home",
  },
  {
    id: 4,
    name: "Result",
    components: <Result />,
    auth: false,
    show: false,
    exact: true,
    index: true,
    icon: "",
    path: "/result",
  },
  {
    id: 5,
    name: "Page Not Found",
    components: <PageNotFound />,
    auth: false,
    show: false,
    exact: true,
    index: true,
    icon: "",
    path: "*",
  },
];
